import { createDeck, toggleDeck } from "@/app/admin/predictions/actions";
import { getDatabase } from "@/lib/db/client";

export const dynamic = "force-dynamic";
const input = "mt-2 h-11 w-full rounded-lg border border-slate-200 px-3 text-sm outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10";

export default async function AdminDecksPage() {
  const decks = await getDatabase().deck.findMany({ include: { _count: { select: { predictions: true } } }, orderBy: { sortOrder: "asc" } });
  return <main className="mx-auto max-w-7xl px-5 py-10 sm:px-8 sm:py-14"><div><h1 className="text-4xl font-black tracking-[-0.05em] text-slate-950">Decks</h1></div><div className="mt-9 grid gap-7 lg:grid-cols-[0.9fr_1.1fr]"><form action={createDeck} className="h-fit rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-black text-slate-950">Create a Deck</h2><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">Name<input name="name" required className={input} /></label><label className="text-sm font-bold text-slate-700">Icon<input name="icon" placeholder="VIP" className={input} /></label><label className="text-sm font-bold text-slate-700 sm:col-span-2">Description<textarea name="description" required minLength={10} rows={4} className="mt-2 w-full rounded-lg border border-slate-200 p-3 text-sm outline-none focus:border-emerald-500" /></label><label className="text-sm font-bold text-slate-700">Visual ID<input name="visualIdentifier" placeholder="emerald" className={input} /></label><label className="text-sm font-bold text-slate-700">Sort order<input name="sortOrder" type="number" min="0" defaultValue="0" className={input} /></label><label className="flex items-center gap-3 text-sm font-bold text-slate-700 sm:col-span-2"><input name="isPremium" type="checkbox" className="size-4 accent-emerald-600" />Premium Deck</label></div><button className="mt-6 min-h-11 w-full rounded-xl bg-[#078a4f] text-sm font-black text-white">Create Deck</button></form><div className="space-y-4">{decks.map((deck) => <article key={deck.id} className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-start justify-between gap-5"><div><div className="flex items-center gap-2"><h2 className="text-lg font-black text-slate-950">{deck.name}</h2>{deck.isPremium && <span className="rounded-full bg-amber-50 px-2 py-1 text-[0.6rem] font-black text-amber-700">PREMIUM</span>}</div><p className="mt-2 text-sm leading-6 text-slate-500">{deck.description}</p><p className="mt-3 text-xs font-bold text-slate-400">{deck._count.predictions} predictions · Sort {deck.sortOrder}</p></div><form action={toggleDeck}><input type="hidden" name="id" value={deck.id} /><input type="hidden" name="isActive" value={String(!deck.isActive)} /><button className={`rounded-lg px-3 py-2 text-xs font-black ${deck.isActive ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{deck.isActive ? "Active" : "Inactive"}</button></form></div></article>)}</div></div></main>;
}
