import { requireAdmin } from "@/lib/auth/authorization";
import { getDatabase } from "@/lib/db/client";
import { updateUserAccess } from "./actions";

const roles = ["SUPER_ADMIN", "ADMIN", "EDITOR", "TIPSTER", "USER"] as const;

export default async function UsersPage() {
  const actor = await requireAdmin();
  const users = await getDatabase().user.findMany({ orderBy: { createdAt: "desc" }, select: { id: true, username: true, email: true, phone: true, displayName: true, role: true, isActive: true, createdAt: true, lastLoginAt: true } });
  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-7 sm:py-10"><p className="text-xs font-black uppercase tracking-[0.14em] text-emerald-600">Access control</p><h1 className="mt-2 text-3xl font-black tracking-[-0.05em] text-slate-950 sm:text-4xl">User Management</h1><p className="mt-3 text-sm text-slate-500">Review contact details, account status and staff roles. Only super administrators can save access changes.</p><div className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="hidden grid-cols-[1.3fr_1fr_0.8fr_auto_auto] gap-4 bg-slate-50 px-5 py-3 text-[0.65rem] font-black uppercase tracking-wide text-slate-400 md:grid"><span>User</span><span>Contact</span><span>Role</span><span>Status</span><span>Action</span></div><div className="divide-y divide-slate-200">{users.map((user) => <form key={user.id} action={updateUserAccess} className="grid gap-4 p-5 md:grid-cols-[1.3fr_1fr_0.8fr_auto_auto] md:items-center"><input type="hidden" name="userId" value={user.id} /><div><p className="font-black text-slate-950">{user.displayName || user.username}</p><p className="mt-1 text-xs text-slate-500">@{user.username} · Joined {user.createdAt.toLocaleDateString("en-GB")}</p></div><div><p className="text-sm font-bold text-slate-700">{user.email}</p><p className="mt-1 text-xs text-slate-400">{user.phone || "No phone number"}</p></div><select name="role" defaultValue={user.role} disabled={actor.role !== "SUPER_ADMIN"} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-xs font-bold text-slate-700">{roles.map((role) => <option key={role}>{role}</option>)}</select><label className="flex items-center gap-2 text-sm font-bold text-slate-600"><input type="checkbox" name="isActive" value="true" defaultChecked={user.isActive} disabled={actor.role !== "SUPER_ADMIN"} className="size-4 accent-emerald-600" />{user.isActive ? "Active" : "Inactive"}</label><button disabled={actor.role !== "SUPER_ADMIN"} className="h-10 rounded-lg bg-[#078a4f] px-4 text-sm font-black text-white disabled:bg-slate-200 disabled:text-slate-500">Save</button></form>)}</div></div></main>;
}
