import { getDatabase } from "@/lib/db/client";
import { createPlan, updatePlan } from "./actions";

const input = "mt-2 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-emerald-500";

export default async function PlansPage() {
  const [plans, decks] = await Promise.all([getDatabase().plan.findMany({ include: { deck: { select: { name: true } } }, orderBy: { sortOrder: "asc" } }), getDatabase().deck.findMany({ where: { isPremium: true, isActive: true }, orderBy: { sortOrder: "asc" } })]);
  const fields = (plan?: typeof plans[number]) => <><label className="text-sm font-bold text-slate-700">Name<input name="name" required defaultValue={plan?.name} className={input} /></label><label className="text-sm font-bold text-slate-700">Price (GHS)<input name="price" type="number" min="0.01" step="0.01" required defaultValue={plan ? (plan.priceMinor / 100).toFixed(2) : undefined} placeholder="Set current price" className={input} /></label><label className="text-sm font-bold text-slate-700 sm:col-span-2">Description<textarea name="description" required minLength={10} defaultValue={plan?.description} rows={3} className="mt-2 w-full rounded-lg border border-slate-200 p-3 text-sm outline-none focus:border-emerald-500" /></label><label className="text-sm font-bold text-slate-700">Duration days<input name="durationDays" type="number" min="1" max="365" required defaultValue={plan?.durationDays ?? 1} className={input} /></label><label className="text-sm font-bold text-slate-700">Scope<select name="scope" defaultValue={plan?.scope ?? "DECK"} className={input}><option value="ALL_PREMIUM">All premium</option><option value="DECK">Specific Deck</option></select></label><label className="text-sm font-bold text-slate-700">Deck<select name="deckId" defaultValue={plan?.deckId ?? ""} className={input}><option value="">None</option>{decks.map((deck) => <option key={deck.id} value={deck.id}>{deck.name}</option>)}</select></label><label className="text-sm font-bold text-slate-700">Sort order<input name="sortOrder" type="number" min="0" defaultValue={plan?.sortOrder ?? 0} className={input} /></label><label className="flex items-center gap-2 text-sm font-bold text-slate-700"><input name="isActive" type="checkbox" defaultChecked={plan?.isActive ?? true} className="size-4 accent-emerald-600" />Show this VIP plan</label><label className="flex items-center gap-2 text-sm font-bold text-red-700"><input name="isSoldOut" type="checkbox" defaultChecked={plan?.isSoldOut ?? false} className="size-4 accent-red-600" />Mark as sold out</label></>;
  return <main className="mx-auto max-w-7xl px-5 py-10 sm:px-8 sm:py-14"><p className="text-xs font-black uppercase tracking-[0.14em] text-emerald-600">Premium pricing</p><h1 className="mt-2 text-4xl font-black tracking-[-0.05em] text-slate-950">VIP Plans</h1><p className="mt-3 text-sm text-slate-500">Prices are stored in the database. Changes appear on the VIP page without a deployment.</p><div className="mt-8 grid gap-6 lg:grid-cols-2"><form action={createPlan} className="h-fit rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-black text-slate-950">Create Plan</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{fields()}</div><button className="mt-6 h-11 w-full rounded-xl bg-[#078a4f] text-sm font-black text-white">Create Plan</button></form><div className="space-y-5">{plans.map((plan) => <form key={plan.id} action={updatePlan} className="rounded-2xl border border-slate-200 bg-white p-6"><input type="hidden" name="id" value={plan.id} /><div className="grid gap-4 sm:grid-cols-2">{fields(plan)}</div><button className="mt-6 h-11 w-full rounded-xl bg-slate-900 text-sm font-black text-white">Save Changes</button></form>)}</div></div></main>;
}
